name: SSH Action

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH
        run: |
          sudo mkdir -p ~/.ssh/
          sudo chmod 777 ~/.ssh
          sudo echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          sudo ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: SSH conect machine
        run: |
          ssh admin@${{secrets.SSH_HOST}} 'bash' <<EOF
          #!/bin/bash
          whoami
          cd /var/www/ipetProject
          ls -la


          #  echo "Iniciando Pull........................................."
          # sudo git pull origin
          # echo "Adicionando permissões.................................."
          # sudo chown -R www-data:www-data /var/www/ipetProject
          # echo "Artisan................................................."
          # sudo php artisan optimize
          # echo "finalizado.............................................."

          EOF


