name: SSH Action

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH
        run: |
          sudo mkdir -p ~/.ssh/
          sudo chmod 777 ~/.ssh
          sudo echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          sudo ssh-keyscan ec2-174-129-173-197.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH into remote machine
        run: |
          ssh admin@ec2-174-129-173-197.compute-1.amazonaws.com
          sudo echo "Iniciando Pull..." >> /home/admin/logPull.txt && date >> /home/admin/logPull.txt
