name: SSH Action

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan hostname >> ~/.ssh/known_hosts

      - name: SSH into remote machine
        run: ssh ubuntu@ec2-54-144-79-207.compute-1.amazonaws.com
