name: SSH Action

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up SSH
        run: |
          sudo mkdir -p ~/.ssh/
          sudo chmod 777 ~/.ssh
          sudo echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 700 ~/.ssh/id_rsa
          sudo ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: SSH conect machine
        run: |
          ssh admin@${{secrets.SSH_HOST}}  'bash -s' << EOF
          #!/bin/bash
          sudo cd /var/www/ipetProject
          sudo echo "Iniciando Pull..." >> /home/admin/logPull.txt
          sudo date >> /home/admin/logPull.txt
          sudo git pull origin >> /home/admin/logPull.txt
          sudo chown -R www-data:www-data /var/www/ipetProject
          sudo php artisan optimize
          sudo echo "finalizado" >> /home/admin/logPull.txt
          EOF


